version: '3.8'

services:
  pyvideoscraper:
    container_name: pyvideoscraper
    image: pyvideoscraper:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
      - ./:/data

    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      
